global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docai-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9999']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}:9999'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
