apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      serviceMap:
        enabled: true
      search:
        enabled: true
      nodeGraph:
        enabled: true
    tracesToMetrics:
      datasourceUid: prometheus
    tracesToLogs:
      datasourceUid: loki
    spanBar:
      type: Tag
      tag: component
    lokiSearch:
      datasourceUid: loki
    metrics:
      datasourceUid: prometheus
    custom:
      httpMethod: GET
    editable: true
