apiVersion: v1
kind: Service
metadata:
  name: docai-backend
  namespace: docai-staging
  labels:
    app: docai-backend
spec:
  type: ClusterIP
  selector:
    app: docai-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: management
      port: 9091
      targetPort: 9091
      protocol: TCP
