apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

namespace: docai-production

patches:
  - path: production-env.yaml
    target:
      kind: Deployment
      name: docai-backend
